default: &default
  encoding: utf8
  adapter: postgresql

development:
  adapter: postgresql
  encoding: unicode
  database: codental_app_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>